name: php-cs-fixer

on: [ workflow_dispatch ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist --working-dir=laravel/tools/php-cs-fixer

      - name: PHP-CS-Fixer Version
        run: ./laravel/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --version
      - id: changed-files
        uses: tj-actions/changed-files
      - id: test
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
      - id: test2
        run: echo ${{ steps.changed-files.outputs.all_changed_files }} | grep -e '.php$' || true
#      - name: PHP-CS-Fixer Dry Run
#        run: |
#          git diff --name-status main | grep -e '^[AM]\(.*\).php$' | cut -c 3- |
#          ./laravel/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=./laravel/.php-cs-fixer.dist.php --verbose --dry-run $(${{ steps.changed-files.outputs.all_changed_files }})
