name: php-cs-fixer

on: [ workflow_dispatch ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist --working-dir=laravel/tools/php-cs-fixer

      - name: PHP-CS-Fixer Version
        run: ./laravel/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --version
      - id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            *.php
      - id: test
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: PHP-CS-Fixer Dry Run
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          xargs --no-run-if-empty ./laravel/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=./laravel/.php-cs-fixer.dist.php --verbose --dry-run
